name: Gif Comment
on:
  issues:
    types: [opened]
  
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add gif comment
        uses: actions/checkout@v2
        id: GifComment
        with:
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
